version: '3.1'
services:
  web:
    image: httpd:2.4
    ports:
      - 8880:80
    volumes:
      - ./:/usr/local/apache2/htdocs/ 

  dgraph:
    image: dgraph/standalone:v21.03.0
    ports:
      - 8000:8000
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3
    hostname: myrabbit

