version: "3"

services:
  api:
    build:
      context: './Server/API'    
    ports:
      - 4000:4000

  client:
    build:
      context: './Client'
    ports:
      - 3000:80

  dgraph-zero:
    image: dgraph/dgraph:latest
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  dgraph-alpha:
    image: dgraph/dgraph:latest
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080