version: '3.1'
services:
  fileserver:
    image: httpd:2.4
    ports:
      - 8888:80
    volumes:
      - ./:/usr/local/apache2/htdocs/ 

  dgraph:
    image: dgraph/standalone:v21.03.0
    ports:
      - 8000:8000
      - 8080:8080
      - 9080:9080
  
  web: 
    image: httpd:2.4
    ports: 
    - 800:80
    - 4430:443
    volumes:
    - ./store/build:/usr/local/apache2/htdocs/




