version: "3.4"

services:
  client:
    build:
      context: './Client'
      target: react
    ports:
      - 80:3000
      - 443:3000
    restart: on-failure
    links:
     - api
  api:
    build:
      context: './Server'
      dockerfile: API-Dockerfile
    ports:
      - 4000:4000
    restart: on-failure
    links:
     - dgraph

  dgraph:
    ports:
      - 8080:8080
    build:
      context: './Server'
      dockerfile: Database-Dockerfile
    restart: on-failure
