version: "3"

services:

  client:
    build:
      context: './Client'
    ports:
      - 3000:80
    restart: on-failure
    depends_on:
      - api 

  api:
    build:
      context: './Server/API'    
    ports:
      - 4000:4000
    restart: on-failure
    depends_on:
     - zero
     - alpha

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080

volumes:
 dgraph:
