version: "3"

services:

  client:
    build:
      context: './Client'
    ports:
      - 3000:80
    restart: on-failure
    depends_on:
      - api 

  api:
    build:
      context: './Server/API'    
    ports:
      - 4000:4000
    depends_on:
      - dgraph
    restart: on-failure

  dgraph:
    image: dgraph/dgraph:latest
    volumes:
    - dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure

volumes:
 dgraph:
